name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: 22
        distribution: temurin
        
    # Compiles all java for .java
    - name: Compile java
      run: javac **/*.java

    # Compiles with warnings enabled
    - name: Compile warnings
      run: javac -Xlint:all **/*.java

    # compile and run with JDK temurin
    - name: temurin JDK  
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - run: java **/*.java
