name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: 22
        distribution: temurin
        
    # Compiles all java for .java
    - name: Compile java
      run: javac **/*.java

    # Runs JUint test for .class
    - name: Run JUnit tests
      run: java -cp ".:path-to-junit.jar" org.junit.runner.JUnitCore **/*.class
      
