name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: 22
        distribution: temurin
        
    # Compiles all java for .java
    - name: Compile java
      run: javac **/*.java

    # Compiles with warnings enabled
    - name: Compile warnings
      run: javac -Xlint:all **/*.java

    # Checkstyle 
    - name: Download Checkstyle
      run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.8/checkstyle-10.8-all.jar

    - name: Run Checkstyle
      run: java -jar checkstyle-10.8-all.jar -c /google_checks.xml **/*.java

    #Coverage report
    - name: Run tests with coverage
      run: ./gradlew test jacocoTestReport
